SCRAPED_DATA_PATH = '/home/ec2-user/think-scraping/data/'
APPANNIE_USERNAME = 'me@timogilvie.com'
APPANNIE_PASSWORD = 'scorpio'
APPANNIE_PASSWORD_HASHED = "PZNSiyIl6g+nDWUtFg0TnZkQ6lNICjAVmE02ejZR3zXxu1J9B281Xc7iFaOrzr4="

APPANNIE_USERNAME2 = 'marcus.albertson1976@gmail.com'
APPANNIE_PASSWORD2 = 'scorpio1'
APPANNIE_PASSWORD_HASHED2 = "yvpXu/v0cU6C0o3o5O3nMEEKQJSKYzzxMz2poMqOwL+3CWBJnmxGtKVIsW6w0CBu"

APPANNIE_USERNAME3 = 'nancy.mcintosh1987@gmail.com'
APPANNIE_PASSWORD3 = 'N@ncy1sGr3at'
APPANNIE_PASSWORD_HASHED3 = "zqUOg8V0zUQ4cn1lVj+8y8tR9xcWkcatHtSxF3rw2DJ+B2I0AFrlQ4TjHOjMoykc+VBrUA=="


APPANNIE_USERNAME4 = 'mattnathanson659@gmail.com'
APPANNIE_PASSWORD4 = 'M@tt123M@tt'
APPANNIE_PASSWORD_HASHED4 = "6/pjs5/GOgjHI8q0fPaoXjL7bBFyVEsX3XmHALWj85GTQEL8oUX7DBCDjvqgd9L63/em"
